### ISSUE TITLE
road-building sometimes hindered by trees

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#9] opened 2019-03-10 23:12 UTC
[B14B-M3-GAME1.zip](https://github.com/Pyrdacor/freeserf.net/files/2950157/B14B-M3-GAME1.zip)
in above savegame it is impossible to build a road northwest of the western flag (very near to the castle), to connect the northern hut, after a double-click it builds a road to the west, totally avoiding the tree (but that alternate road is not very useful)

**Comment by Pyrdacor** [comment] 2019-03-11 16:36
The problem is that the mouse click is not considered at the right spot. You can see this if you try to select the spot without building the road. Transferring the mouse position to the ingame position is a bit tricky and not always perfect yet.

But when double-clicking the flag of the hut, this should not happen. It doesn't happen for me. Maybe you could show me a screenshot of the road the double click caused in your case.

**Comment by Pyrdacor** [comment] 2019-03-11 17:14
I finally found a bug in the calculation and fixed it. As this bug was crucial and in there for a long time I created a new version (v1.5). Please try again with this new version.

**Comment by JSettler** [comment] 2019-03-11 20:51
(i double-clicked the icon which was not clickable (in 1.4); the new version i'll test soon..)

**Comment by JSettler** [comment] 2019-03-11 21:01
"Build14Game1" still has that problem, can the bug resurface when loading a game saved with v1.4? if yes, then i'll just delete all old saves and test with a new game, else i can upload that save.

**Comment by JSettler** [comment] 2019-03-11 21:01
(i tested that old save within v1.5)

**Comment by Pyrdacor** [comment] 2019-03-11 21:09
It has nothing to do with the savegame. It was a bug in mouse coordinate transformation. If it still happens with v1.5 it is strange. I can build the road as expected. I did not test double clicking yet but normal step by step build should work now. If not please describe how you exactly do it and what happens.

**Comment by JSettler** [comment] 2019-03-11 21:25
ok tested v1.5, now a new (but related?) problem showed up: i can't select the building-plot of a hut northwest of blue's castle in this savegame (a demo-game with 4 AIs):
[B15-M3-DEMO1.zip](https://github.com/Pyrdacor/freeserf.net/files/2954250/B15-M3-DEMO1.zip)
i tried to click near the plot (after trying to click it exactly) but it only selects nearby places. is there a way to rotate the view?

**Comment by JSettler** [comment] 2019-03-11 21:34
[BUILD14GAME1_(2).zip](https://github.com/Pyrdacor/freeserf.net/files/2954276/BUILD14GAME1_.2.zip)
in that savegame i cant connect the 2 unconnected flags properly, if i start at the castle flag, i cant select any of the two 0%-gradient roads; and if i start with the huts flag and select the yellow-gradient road it takes another road (making a detour)

**Comment by Pyrdacor** [comment] 2019-03-12 10:42
Build v1.6 should improve the behavior. It is still not perfect but should work better now.

**Closed** 2019-03-16 20:18 UTC
Labels: bug
