### ISSUE TITLE
Mouse map scrolling

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#112] opened 2020-06-02 09:28 UTC
Trying to scroll map using right mouse button jumps to current pointer location instead of smooth scrolling using mouse movement. I'm not sure if this is intentional but if it is; make an option to disable it.

![Freeserf](https://i.imgur.com/PpuTUX0.gif)

**Comment by Pyrdacor** [comment] 2020-06-02 12:42
This is not intentional and I can't reproduce it. It scrolls smoothly on my end. Which OS and version did you use and did you do something before that? Which game mode (mission, AIvsAI, etc) was it. Does it happen all the time? If so which game options are active?

**Comment by GORE84** [comment] 2020-06-02 23:03
I'm using Win7 and v2.0.1. I just point to a corner and holding mouse2 button down and move it will jump to the location and from there it scrolls normally. I play vs AI.

**Comment by GORE84** [comment] 2020-06-03 23:27
The issue started in the v2.0.0-preview6. Preview 5 has normal behavior.

**Comment by Pyrdacor** [comment] 2020-06-04 06:59
Does this happen every time or only once? Does it only happen in corners?

**Comment by GORE84** [comment] 2020-06-04 07:55
Happens every time I move map. Anywhere on screen. It centers the screen where the mouse pointer is located.

**Comment by Pyrdacor** [comment] 2020-06-04 12:04
Is the option "Reset cursor after scrolling" active? If so, does it happen when it is deactivated?

**Comment by Pyrdacor** [comment] 2020-06-04 18:06
Ok I managed to setup a win7 machine and could reproduce your issue. Will dig deeper into it with a VM.

**Comment by Pyrdacor** [comment] 2020-06-05 12:38
Should be fixed in v2.0.3

**Closed by Pyrdacor** 2020-06-05 12:38 UTC
Labels: bug
