### ISSUE TITLE
Serfs are in an endless que on path

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#72] opened 2019-11-23 13:06 UTC
It looks like nobody wants to take the first step transporting goods to castle.

Saved games of two AI playing:
[SAVE1](http://s000.tinyupload.com/index.php?file_id=93340696043002758567)
[SAVE2](http://s000.tinyupload.com/index.php?file_id=04796591461582096477)

**Comment by Pyrdacor** [comment] 2019-12-08 16:51
Can you try with v1.9.27? The old savegames will not fix imho. But I hope new games will not be affected.

**Comment by Pyrdacor** [comment] 2020-01-05 10:29
Duplicate of #73

**Closed** 2020-01-05 10:29 UTC
Labels: bug
