### ISSUE TITLE
game freeze

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#10] opened 2019-03-11 23:10 UTC
i recalled that yesterday i got a game-freeze while watching a (very high) accelerated AI-only game, in the log it said something like "[building] yielded an unexpected resource" or so, sadly i didnt have that log anymore and forgot to save the game before the crash/freeze, sorry :/
Now i try to reproduce that bug with a similar game (both on mapsize 3, with 4 AIs which have all color bars maxed)

**Comment by JSettler** [comment] 2019-03-11 23:22
[B15-M3-DEMO1_(2)[continued].zip](https://github.com/Pyrdacor/freeserf.net/files/2954546/B15-M3-DEMO1_.2.continued.zip)
the game ran for approx. 0.5 - 1.5 minutes with +100 speed (i pressed the plus-key a hundred times), then i saved it (while paused), but then the reload failed with error "game could not be loaded".
i guess that the speed was too high and is making the game unstable?

**Comment by JSettler** [comment] 2019-03-11 23:26
the log says: "Error: [savegame] Failed to load save game: The input string is in the wrong format."

**Comment by JSettler** [comment] 2019-03-12 00:13
uh.. now i got the exact same error message with a normal-speed game (which i played for longer, at least 10-20 minutes or so) after trying to load it: 
[B15-M3-GAME1.zip](https://github.com/Pyrdacor/freeserf.net/files/2954646/B15-M3-GAME1.zip)
sorry for digging out so many bugs and no need to rush.

**Comment by Pyrdacor** [comment] 2019-03-12 06:01
No need to apologize. I really appreciate your help in testing and finding bugs. I don't think the game loading fails have something to do with the game speed. I will have a look at it later this day.

**Comment by Pyrdacor** [comment] 2019-03-13 07:22
These are two things. The game freeze might be a performance issue. I will have a look at it later.

The game loading error was a bug in the game saving function. I fixed it in v1.7 but it won't repair your savegames. It only avoids creating corrupt savegames from now on. To repair your savegame you have to do it manually. Simply open the savegame in a text editor of your choice and search for "mineral". There should be lines that start with "mineral_coal_0_pos" or something similar. Delete all those lines and save the file. Now you should be able to load the savegame again. The AI will lose its knowledge about mineral spots but this is ok as they will look for minerals again.

Please try it and tell me how it went. If you can load it after repairing, you could save it again inside the game. It should be still loadable then hopefully.

**Comment by JSettler** [comment] 2019-03-13 23:20
Thanks, but the old savegames are not that important, i'll just start new games with the latest version to have maximum long-term stability (i prefer to minimize technical risks for longer and serious games).

The freeze resurfaced in a new game (started in v1.7) and created that log: "Error: [render] Index out of array range." (while running a 4-AI-demo with max. speed for at least ~10-15 minutes)
i'll try to make a save just before the freeze (even if it will be difficult) later or when there is a new version (because of the other savegame issue).
Could these two issues be related?

**Comment by Pyrdacor** [comment] 2019-03-15 05:52
I hopefully fixed that bug. I also ensured that hard crashes are avoided and instead a window is shown with message and stack trace. Because this changes are very helpful I created a full new version v1.8. But you could also use the patcher to get this version.

**Comment by JSettler** [comment] 2019-03-17 01:07
It froze again after a long game (~30-40 minutes) on mapsize 5 vs 3 AIs :(
and i thought it was stable.. but now i even have no savegame, because it took me by surprise while i was totally in-the-flow.
(i had to close it with taskman)
In the AI-only demos of 1.8.3 i had no freezes (yet).
It seems, i have to make a long (speedrun-) test in single-player mode (vs 3 maxed AIs) in mapsize 5, but this time with just my castle set to see if it freezes then, if not, it must have something to do with long interactive player sessions..

**Comment by Pyrdacor** [comment] 2019-03-17 05:35
I had this crash once too. It was an error inside the depth of the game logic that is hard to track. Rare bugs are the worst. The question is why the game crashes instead of showing the normal error message. In the crash case the error occurred in some Windows internal native code. This code is called when trying to show the error message box. Therefore it crashes that hard and the message box is not shown. Unfortunately I can't see the code of Windows internals. But I will look at this more deeply.

**Comment by Pyrdacor** [comment] 2019-03-17 05:37
Did the freeserf log file contain information?

**Comment by JSettler** [comment] 2019-03-17 17:49
It already got overwritten, sorry :/

But maybe this tool can help in that cases: https://x64dbg.com/

**Comment by JSettler** [comment] 2019-03-18 01:06
Gotcha.
It was this error message "Error: [FrameTimer] [building]Delivered unexpected resource."
Hard crash("freeze") happened few minutes (speedrun) after the last save(no.4) of this game:
[b191.map5-4ai-demo2.zip](https://github.com/Pyrdacor/freeserf.net/files/2975972/b191.map5-4ai-demo2.zip)

**Comment by Pyrdacor** [comment] 2019-03-18 07:21
This does not happen for me. Tested multiple times. So I guess this is a random bug. I know this error but could not find out how it happens as this is deep inside the serf logic and there are too many serfs to track this properly. But I got another error which I could fix. A patch will follow in the evening.

**Comment by Pyrdacor** [comment] 2019-03-19 00:38
Seems that this is also the root cause in the other thread so I close this one.

**Closed by Pyrdacor** 2019-03-19 00:38 UTC
Labels: bug
