### ISSUE TITLE
Serfs stops transporting material

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#73] opened 2019-11-23 17:00 UTC
Image attached:
![freeserf](https://user-images.githubusercontent.com/19464573/69482400-78b51900-0e23-11ea-93a1-07643281e1eb.jpg)

**Comment by Pyrdacor** [comment] 2019-11-24 13:18
Thanks for the report. I redesigned the code to ease development for me and others. But there seem to be new bugs because of that. I will fix them when I got some time on hands. If you want to enjoy the game experience you can go back to v1.9.24 for now.

**Comment by Pyrdacor** [comment] 2019-12-08 16:50
Can you try with v1.9.27? The old savegames will not fix imho. But I hope new games will not be affected.

**Comment by GORE84** [comment] 2019-12-08 17:34
It seems the bug is still there. Serf stops transporting but after a while a second Serf comes and does the job instead.
![freeserf02](https://user-images.githubusercontent.com/19464573/70393349-907ac880-19f1-11ea-9574-8e4b83d56ee4.jpg)

**Comment by GORE84** [comment] 2020-01-05 08:52
Bumping this with another picture. Are the workers on a strike?  :)
![freeserf03](https://user-images.githubusercontent.com/19464573/71777494-75c45100-2fa9-11ea-8861-54c3ad67b916.jpg)

**Comment by Pyrdacor** [comment] 2020-01-05 09:41
:grin:
I will have a look at it. It's hard to track as it seem to happen only from time to time.

**Comment by Pyrdacor** [comment] 2020-01-08 14:27
Does this occur often? I couldn't reproduce this issue. Maybe you could provide a savegame?

**Comment by GORE84** [comment] 2020-01-09 15:58
Like every game for me. I have two AI play against each other.

Now this latest game the blue player has one serf refusing to transport fish to the miners.
[Savegame](http://s000.tinyupload.com/index.php?file_id=44161800418871881092)

**Comment by Pyrdacor** [comment] 2020-01-12 02:23
After many hours of game debugging I finally found a huge issue related to all serf states in the game. I hopefully fixed it now. This will fix many game related issues but I guess some old savegames won't be fully fixed. But at least new games should run much better now.

Please give it a shot with v1.9.29. Thanks for your patience.

**Comment by GORE84** [comment] 2020-01-12 07:26
Firing up a fresh game with AI playing, their stone cutters goes out in the wild and doesnt do their job
![freeserf04](https://user-images.githubusercontent.com/19464573/72215603-829ef280-351d-11ea-98fb-f0755888cfb0.jpg)

**Comment by Pyrdacor** [comment] 2020-01-12 11:40
Damn it. :) OK will have a look at it.

**Comment by Pyrdacor** [comment] 2020-01-12 16:53
Should be fixed in v1.9.30.

**Comment by GORE84** [comment] 2020-01-13 07:41
Using version 1.9.31 this bug still occurs unfortunately...
Serf hiding behind castle refuses to do his job.
![freeserf05](https://user-images.githubusercontent.com/19464573/72239172-c90d5380-35e8-11ea-95d1-3adbab5686c3.jpg)

**Comment by Pyrdacor** [comment] 2020-01-13 18:44
I can't reproduce this issue with v1.9.31. Are you sure you are using this version? Is it displayed in the main UI window on startup? Can you provide a savegame again please?

**Comment by Pyrdacor** [comment] 2020-01-13 23:32
I fixed a few more issues in v1.9.32. Maybe it is better now?

**Closed** 2020-01-15 07:12 UTC
Labels: bug
