### ISSUE TITLE
Crash: No error

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#59] opened 2019-04-03 23:43 UTC
Crash about 2 hours into a 3 player game. No error given, just default Windows crash: 

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	Freeserf.net.exe
  Application Version:	1.9.17.0
  Application Timestamp:	946127f1
  Hang Signature:	8edc
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Hang Signature 1:	8edc4e523ca2edb4c4cd678fb69df160
  Additional Hang Signature 2:	d99d
  Additional Hang Signature 3:	d99db8a711eb62635eb9a0e6719c1b09
  Additional Hang Signature 4:	8edc
  Additional Hang Signature 5:	8edc4e523ca2edb4c4cd678fb69df160
  Additional Hang Signature 6:	d99d
  Additional Hang Signature 7:	d99db8a711eb62635eb9a0e6719c1b09

**Comment by Pyrdacor** [comment] 2019-04-05 14:31
Can you describe what you did before the crash? Did you click or dragged something?

**Comment by Vershner** [comment] 2019-04-05 15:08
I think I was scrolling with the right mouse button.

**Comment by Pyrdacor** [comment] 2019-04-23 09:33
This error occurs if a UI event takes too long. For example dragging (scrolling the map or minimap) is an UI event. When scrolling the map or minimap, the visible portion of the map is re-rendered and the minimap is updated. If this takes too long this crash may occur. Maybe there was too much stuff to render. I don't have a good solution for this yet, but I will work on it.

**Comment by GORE84** [comment] 2019-10-15 08:54
Game crashed when I was idling. Just watching those serf working and suddenly everything freezes. :(

**Comment by Pyrdacor** [comment] 2019-10-15 10:36
Did you moved the mouse or pressed a mouse button just before the freeze?

**Comment by GORE84** [comment] 2019-10-15 18:35
I'm not 100% sure but maybe I moved the mouse. I didnt scroll the map. I was pretty far in the game vs AI.
I'll try play couple more games and take note when it crashes...

**Comment by Pyrdacor** [comment] 2019-10-15 19:21
Those freezes are hard to track but I bet it freezes in some input events like mouse moving. Maybe I'll be able to find the issue. Next time please also have a look in the log file.

**Comment by GORE84** [comment] 2019-10-15 23:33
This time I did nothing. Not even moved mouse. Was 4 AI in game and no players.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	Freeserf.net.exe
  Application Version:	1.9.20.0
  Application Timestamp:	ef5d4b2b
  Hang Signature:	b4ee
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1035
 Additional Hang Signature 1:	b4ee5de6a2322745523997a782b35692
  Additional Hang Signature 2:	277e
  Additional Hang Signature 3:	277e19c30fbd5f6bb531ec9e027c37c3
  Additional Hang Signature 4:	b4ee
  Additional Hang Signature 5:	b4ee5de6a2322745523997a782b35692
  Additional Hang Signature 6:	277e
  Additional Hang Signature 7:	277e19c30fbd5f6bb531ec9e027c37c3

**Comment by Pyrdacor** [comment] 2019-10-16 05:58
AppHangB1 kann laut Internetrecherche auch an der Grafikkarte oder anderer Hardware liegen. Mit Google findest du dazu einige Lösungsansätze. Ich schau sonst mal was es im Code sein könnte.

**Comment by Pyrdacor** [comment] 2019-10-16 06:02
I searched with Google for AppHangB1. Many sites say that it is often caused by the display adapter or other hardware. Maybe you could try the solutions there while I try to find out some problem in the code base.

**Comment by GORE84** [comment] 2019-10-18 20:01
Is there a way to enable some debugging to help locate the problem?

**Comment by Pyrdacor** [comment] 2019-10-19 08:53
Hm I fear not. At least nothing which will help with app freezing. Those bugs are very hard to track, even with a full debugging system. Your best chance is to checkout the sources, run Visual Studio Community or an IDE of your choice and run the game via debugger.

**Comment by GORE84** [comment] 2019-10-20 16:40
Unfortunately I have not space to install IDE on this computer.
This error only occurs when AI is in game. No errors occur on single player.

**Comment by GORE84** [comment] 2019-10-28 19:55
So I've been trying the same with two other computers with Win10 and same thing happens. Putting one AI to play and after a while it freezes.

**Comment by GORE84** [comment] 2019-11-22 20:11
After update I stumbled on another crash while two AI played against each other.

Game crashed when I double clicked on one of their main castle.

> Problem signature:
>   Problem Event Name:	CLR20r3
>   Problem Signature 01:	Freeserf.net.exe
>   Problem Signature 02:	1.9.25.0
>   Problem Signature 03:	dee54abe
>   Problem Signature 04:	Freeserf.Core
>   Problem Signature 05:	1.0.0.0
>   Problem Signature 06:	b3f20265
>   Problem Signature 07:	93b
>   Problem Signature 08:	0
>   Problem Signature 09:	System.StackOverflowException
>   OS Version:	6.1.7601.2.1.0.768.3
>   Locale ID:	1035
>   Additional Information 1:	8f5b
>   Additional Information 2:	8f5baa42ad2a4938c9f8ed1c9f8b29c3
>   Additional Information 3:	0f6a
>   Additional Information 4:	0f6a3c376cfdb539869e0f998570c535
>

**Comment by Pyrdacor** [comment] 2019-11-23 12:42
The last crash should be fixed in v1.9.26.

**Comment by Pyrdacor** [comment] 2019-12-22 12:45
I will close this for now. When similar issues occur please feel free to reopen this.

**Comment by GORE84** [comment] 2020-01-12 19:15
This crash still occurs. Unable to play long games.

**Comment by Pyrdacor** [comment] 2020-01-12 19:30
Ok I will try to track and fix this

**Comment by Pyrdacor** [comment] 2020-01-12 23:31
I fixed a few issues and an infinite loop that may has caused the crash. Please check v1.9.31.

**Comment by Pyrdacor** [comment] 2020-01-13 00:22
I think there are still freezes. Have to look further. I am running long time AI games with debugger. Maybe I can catch some more issues.

**Comment by Pyrdacor** [comment] 2020-01-13 23:33
I fixed another freeze issue. Hopefully freezes are gone now. Please test.

**Closed by Pyrdacor** 2020-01-13 23:33 UTC
Labels: bug
