### ISSUE TITLE
Error while under attack: "Failed to decrease serf count"

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#23] opened 2019-03-21 01:00 UTC
Version: B1.9.4
Type: 1-player game
Map size: 3
No. of AIs: 3 (maxed)
Log file: "Error: [FrameTimer] [player]Failed to decrease serf count"
Circumstances:
After reducing the number of knights in the bordering huts, the yellow AI attacked the nearest one and managed to kill a knight. Right before he killed the second(and last one) the error popped up.

[player] Failed to decrease serf count

========== Stack Trace: ==========

    at Freeserf.Player.DecreaseSerfCount (Type type)
    at Freeserf.Serf.SetFightOutcome (Serf attacker, Serf defender)
    at Freeserf.Serf.HandleSerfKnightPrepareAttacking ()
    at Freeserf.Serf.Update ()
    at Freeserf.Game.UpdateSerfs ()
    at Freeserf.Game.UpdateVisuals ()
    at Freeserf.Game.Update ()
    at Freeserf.UI.Interface.Update ()
    at Freeserf.LocalSpectatorViewer.Update ()
    at Freeserf.Renderer.OpenTK.GameView.Render ()
    at Freeserf.FreeserfForm.FrameTimer_Tick (Object sender, EventArgs e)

[b194-m3-game1.zip](https://github.com/Pyrdacor/freeserf.net/files/2990572/b194-m3-game1.zip)
(crash save file included)

**Comment by Pyrdacor** [comment] 2019-03-22 07:13
I may fixed this as well in patch 1.9.5. But maybe you could try to reproduce the error and look if it still happens. It seemed that the number of knights is decreased twice when a knight dies in fight. Therefore after a few fights the game thinks that there are no more knights. If one dies then, the game reports an error because the knight count goes below zero which could not happen. The same was true for military score. Both should be fixed now I hope.

**Comment by JSettler** [comment] 2019-03-22 12:12
Thanks, will test 1.9.5 in ~8.5-10 hours.

**Closed** 2019-03-27 14:56 UTC
Labels: bug
