### ISSUE TITLE
Crash after loading a 1.8.4 savegame with 1.9

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#18] opened 2019-03-17 18:41 UTC
MessageBox said "loaded successfully", but after click on exit it crashed.
Log: "Error: [FrameTimer] The object reference was not set to an object instance."
with savegame:
[B184-MAP5-VS-3AI-SAVE3.zip](https://github.com/Pyrdacor/freeserf.net/files/2975547/B184-MAP5-VS-3AI-SAVE3.zip)
(in that savegame the AIs have also become seemingly static again, in v1.8.4)

Edit: Thankfully i can load 1.9.1-saves into 1.9.1. So it's only a minor issue.
And the 4 AIs now placed their castles really fast (on a size-9 map)! Thank you again.

**Comment by Pyrdacor** [comment] 2019-03-18 19:52
Could not reproduce with the savegame so I close this.

**Closed by Pyrdacor** 2019-03-18 19:52 UTC
