### ISSUE TITLE
Serf's stops transforming material to buildings.

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#68] opened 2019-10-26 20:51 UTC
AI playing and his second Iron Foundry is missing wood.
Savegame available [here](https://filebin.net/75fxvex812gieyb0/BUG01.save?t=p9eqekyd).

**Comment by Pyrdacor** [comment] 2019-10-28 20:11
Will check this later. ;)

**Comment by Pyrdacor** [comment] 2019-10-30 19:21
Ok I checked. The problem is that the building needs stones and not planks. I know it seems to need planks but the code says "plank -> plank -> stone -> plank -> stone" so the last bit is made of stone. The AI has no stone in castle so the building is not finished.

I could change the order to "plank -> plank -> stone -> stone -> plank" but I want to keep it as close to original game as possible. Maybe someone could check how the order is in original game because I'm not sure about it.

But at least this is not a real bug. So I close this.

**Closed by Pyrdacor** 2019-10-30 19:21 UTC
Labels: bug
